### ISSUE TITLE
Implement new CSAND-style

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-csand#2]
Update output styling to https://github.com/riboseinc/csand-style

**Comment by opoudjis** [comment]
Am waiting for https://github.com/riboseinc/csand-style/issues/1 to complete; the CSAND gem is ready for it now, and in the meantime is using CSD styling.

**Comment by opoudjis** [comment]
Done. Will keep open for  if @pierrefortier will make any further changes.

**Comment by ronaldtse** [comment]
Thanks @opoudjis! What a productive day.

**Comment by ronaldtse** [comment]
@opoudjis the styling on https://github.com/riboseinc/csand-style master branch is ready to be integrated, it's all yours. Thanks!
